### ISSUE TITLE
Hidden alif and waqf sign in 19:26 on Firefox

### ISSUE THREAD

**Issue by kritixilithos** [quran/quran.com-frontend-v2#221]
[This issue](https://github.com/quran/quran.com-frontend/issues/645) from the previous frontend regarding 19:26 is still reproed on Firefox (tested on 81.0.2). The alif in front of "ٱحَدًا" is hidden at font sizes up to 80, but is visible at font size 82. Additionally, the punctuation mark

>  ۖ

remains partially hidden in both font sizes.

![Screenshot of the above, showing both the hidden alif and the hidden waqf sign](https://user-images.githubusercontent.com/13890616/96139568-a60d2880-0f07-11eb-9890-0baef3f7cf85.png)

In 28:45, the punctuation mark

>  ۚ

also is partially hidden.

![Screenshot of the above, showing the missing waqf sign](https://user-images.githubusercontent.com/13890616/96139983-13b95480-0f08-11eb-8d66-ac7c7f7a6632.png)

No repro for any of the above on Opera.

**Comment by naveed-ahmad** [comment]
@kritixilithos jazakAllah kharain for reporting. Finally, this is fixed.

**Comment by kritixilithos** [comment]
wa iyyaak, thanks for the quick fix.

**Comment by kritixilithos** [comment]
@naveed-ahmad Unfortunately, the problem persists at larger font sizes, both the alif and the waqf sign get more hidden as the font size increases.

**Comment by naveed-ahmad** [comment]
@kritixilithos we fixed the bigger font as well. Can you please confirm?

**Comment by kritixilithos** [comment]
@naveed-ahmad Unfortunately it's still not fixed for the larger font, and it looks like the waqf sign is back to being partially hidden in the small font.
